export enum BlendMode {
    COLOR = 'color',
    COLOR_BURN = 'color-burn',
    COLOR_DODGE = 'color-dodge',
    COPY = 'copy',
    DARKEN = 'darken',
    DESTINATION_ATOP = 'destination-atop',
    DESTINATION_IN = 'destination-in',
    DESTINATION_OUT = 'destination-out',
    DESTINATION_OVER = 'destination-over',
    DIFFERENCE = 'difference',
    EXCLUSION = 'exclusion',
    HARD_LIGHT = 'hard-light',
    HUE = 'hue',
    LIGHTEN = 'lighten',
    LIGHTER = 'lighter',
    LUMINOSITY = 'luminosity',
    MULTIPLY = 'multiply',
    OVERLAY = 'overlay',
    SATURATION = 'saturation',
    SCREEN = 'screen',
    SOFT_LIGHT = 'soft-light',
    SOURCE_ATOP = 'source-atop',
    SOURCE_IN = 'source-in',
    SOURCE_OUT = 'source-out',
    NORMAL = 'source-over',
    XOR = 'xor',
}
